### ISSUE TITLE
Missing music

### ISSUE THREAD

**Issue by J013k** [isage/REminiscence-vita#1]
I am not sure if I have done something wrong,
but in intro and after starting new game I do not have any music (MIDI).

On PC everything is fine.
Changing audio card does not help either.

**Comment by isage** [comment]
Which version of assets are you using?
And what do you mean by "changing audio card"?

**Comment by J013k** [comment]
I am not sure what do you mean by assets...
I used "REminiscence-0.4.6.vpk" to install the game.
Copy all the files from `DATA` folder of this game into `ux0:/data/RMSC00001/DATA`.

I can only choose an audio card on PC in the configuration menu:
![https://i.postimg.cc/wBR2nkL8/flash1.png](https://i.postimg.cc/wBR2nkL8/flash1.png)
Music configuration:
![https://i.postimg.cc/52d86MFG/flash1-music.png](https://i.postimg.cc/52d86MFG/flash1-music.png)
Sound configuration:
![https://i.postimg.cc/FRBLmt4T/flash1-sound.png](https://i.postimg.cc/FRBLmt4T/flash1-sound.png)
Save settings and exit:
![https://i.postimg.cc/vmm7dtnH/flash1-save.png](https://i.postimg.cc/vmm7dtnH/flash1-save.png)

On PC game has music & SFX.
While on Vita it does not have any music, it has got only SFX.

**Comment by isage** [comment]
I've meant amiga/pc/pc cd.
That looks like pc, I'll check

**Comment by J013k** [comment]
Yes, first version for the PC.
**Not** the PC CD.
Thanks.

**Comment by isage** [comment]
Ok, so. https://github.com/isage/REminiscence-vita/blob/master/README.txt#L24
reminiscence needs either music dir from Amiga or https://www.exotica.org.uk/wiki/Flashback mod files

**Comment by J013k** [comment]
Thank you.

Additionally for PC version theses audio files need to be copied into `ux0:/data/RMSC00001/DATA`.
There will **not** be any music when these files will be in `ux0:/data/RMSC00001/Music`.

Best regards.
